spring:
  profiles:
    active:
    - dev
foo:11111
---
spring:
  profiles: dev     #开发环境
  application:
    name: server-config-dev
foo:11111
---
spring:
  profiles: test   #测试环境
  application:
    name: server-config--test
foo:11111
  #  请保存为UTF-8格式



